server:
  tomcat:
    min-spare-threads: 3
  port: 80

spring:
  redis:
    host: ${redis.host}
    port: 7001
    password: 123456
  datasource:
    url: jdbc:mysql://${db.host}:3306/test
    username: root
    password: 123456